store:
  name: store1
  address: vijayawada3
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacydb
    username: piper
    password: lps758
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  config:
    import:
      -  configserver:http://localhost:2030
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - refresh

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:2031/eureka

